---
title: "Estimativas - Bayesianas (TGCA)"
author: "André"
date: "12/07/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library('forecast')
library('rstan')
library('ggplot2')
library('bayesplot')
library('survival')
source('gompertz.R')

bayesplot_theme_set(theme_minimal())
```

## Relatório de Estimativas Bayesianas (conjunto TGCA)

```{r funcoes}
log_veros = function(par, tempos, cens){
  return(sum(cens*dgompertz(tempos, par[1], par[2], ln = T) +
               (1 - cens)*pgompertz(tempos, par[1], par[2], ln = T, lower.tail = F)))
}

log_veros_mix = function(par, tempos, cens){
  return(sum(cens*log(1-par[3]) + cens*dgompertz(tempos, par[1], par[2], ln = T) + 
               (1- cens)*log(par[3]  + (1-par[3])*(1 - pgompertz(tempos, a = par[1], b = par[2])))))
}

log_veros_def = function(par, tempos, cens){
  return(sum(cens*flexsurv::dgompertz(tempos, par[1], par[2], log = T) +
               (1 - cens)*flexsurv::pgompertz(tempos, par[1], par[2], log = T, lower.tail = F)))
}

calcula_dic = function(tempos, cens, log_veros, cadeia_a, cadeia_b, cadeia_p = NULL){
  a = mean(cadeia_a)
  b = mean(cadeia_b)
  
  if(!is.null(cadeia_p)){
    p = mean(cadeia_p)
    par = c(a,b,p)
    aux = numeric(length = length(cadeia_a))
    
    for(i in 1:length(cadeia_a)){
      aux[i] = log_veros(c(cadeia_a[i],cadeia_b[i], cadeia_p[i]), tempos, cens)
    }
    
    p_dic = 2*(log_veros(par, tempos, cens) - mean(aux))
    
    dic = -2*log_veros(par, tempos, cens) + 2*p_dic
  }
  else{
    par = c(a,b)
    aux = numeric(length = length(cadeia_a))
    
    for(i in 1:length(cadeia_a)){
      aux[i] = log_veros(c(cadeia_a[i],cadeia_b[i]), tempos, cens)
    }
    
    p_dic = 2*(log_veros(par, tempos, cens) - mean(aux))
    
    dic = -2*log_veros(par, tempos, cens) + 2*p_dic
  }
  return(dic)
}
```

## TGCA

```{r tgca_fit}
dados_tg = read.csv('dados_tg.csv')

#### Modelo usual

#fit_usual_1_cadeia = stan(file = 'codigos_stan/usu_tgca.stan',
#            data = list(N = nrow(dados_tg), T = dados_tg$tempo/365, D = dados_tg$cens), 
#            iter = 11000, warmup = 1000, chains = 1, cores = 1, seed = 154)

fit_usual = stan(file = 'codigos_stan/usu_tgca.stan',
            data = list(N = nrow(dados_tg), T = dados_tg$tempo/365, D = dados_tg$cens), 
            iter = 6000, warmup = 1000, chains = 2, cores = 2, seed = 154)

```

```{r intervals}
color_scheme_set("brewer-Spectral")
mcmc_dens_overlay(fit_usual, pars = c("a", "b")) +
  guides(colour = guide_legend("Cadeia")) 
```

```{r traco mini}
mcmc_trace(fit_usual, window = c(1,1000), pars = c("a", "b"),
           facet_args = list(nrow = 2))

```

```{r traco cheio}
mcmc_trace(fit_usual, pars = c("a", "b"),
           facet_args = list(nrow = 2))  +
  guides(colour = guide_legend("Cadeia")) 
```
```{r}

fig_tgca = gridExtra::grid.arrange(mcmc_dens_overlay(fit_usual, pars = c("a", "b")) +
  guides(colour = guide_legend("Cadeia")),  
  mcmc_trace(fit_usual, pars = c("a", "b"),
           facet_args = list(nrow = 2))  +
  guides(colour = guide_legend("Cadeia")))

ggsave("figuras/conv_tgca.pdf", fig_tgca, units = "in", height = 7, width = 7)

```



```{r acf2}
cadeias_df = data.frame(index = 1:length(extract(fit_usual, "a")), a = extract(fit_usual, "a"), b = extract(fit_usual, "b"))

n = 2000

acf_a = ggAcf(cadeias_df[1:n,]$a, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(a))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

acf_b = ggAcf(cadeias_df[1:n,]$b, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(b))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

gridExtra::grid.arrange(acf_a, acf_b)
```

```{r divergent}
lp_cp = log_posterior(fit_usual)
np_cp = nuts_params(fit_usual)

#mcmc_parcoord(as.array(fit_usual), pars = c("a","b"), np = np_cp)

mcmc_trace(fit_usual, pars = c("a","b"), np = np_cp) +
  xlab("Iterações")
```
```{r divergence}
mcmc_nuts_divergence(np_cp, lp_cp)
```

```{r rhat}
rhats <- rhat(fit_usual)
mcmc_rhat(rhats)
```

```{r}
neff_ncp = neff_ratio(fit_usual, pars = c("a", "b"))
mcmc_neff(neff_ncp)
```
### Recuparando as estimativas e calculando as medidas:
```{r calcula metricas}

fit_usual_summary = summary(fit_usual)

fit_usual_summary$summary

fit_usual_summary$summary[,'50%']

tgca_a = fit_usual_summary$summary[,'50%']['a']
tgca_b = fit_usual_summary$summary[,'50%']['b']

calcula_dic(dados_tg$tempo/365, dados_tg$cens, log_veros,
           extract(fit_usual, "a") |> unlist(),
           extract(fit_usual, "b") |> unlist(), NULL) |>
  print(digits = 22)

```

```{r tgca_fit_mix}
fit = stan( file = 'codigos_stan/mix_tgca.stan',
            data = list(N = nrow(dados_tg), T = dados_tg$tempo/365, D = dados_tg$cens), 
            warmup = 1000, iter = 6000, chains = 2, cores = 2, seed = 154)

```

```{r tgca_intervals_mix}
mcmc_dens_overlay(fit, pars = c("a", "b", "theta"))
```

```{r tgca_traco_mini}
mcmc_trace(fit, window = c(1,1000), pars = c("a", "b", "theta"),
           facet_args = list(nrow = 2))

```

```{r tgca_traco_cheio}
mcmc_trace(fit, pars = c("a", "b", "theta"),
           facet_args = list(nrow = 2))

```


```{r tgca_acf2}
cadeias_df = data.frame(index = 1:length(extract(fit, "a")), a = extract(fit, "a"), b = extract(fit, "b"), theta = extract(fit, "theta"))

n = 2000

acf_a = ggAcf(cadeias_df[1:n,]$a, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(a))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

acf_b = ggAcf(cadeias_df[1:n,]$b, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(b))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

acf_theta = ggAcf(cadeias_df[1:n,]$theta, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(pi))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

gridExtra::grid.arrange(acf_a, acf_b, acf_theta)
```

```{r tgca_divergent}
lp_cp = log_posterior(fit)
np_cp = nuts_params(fit)

#mcmc_parcoord(as.array(fit), pars = c("a","b"), np = np_cp)

mcmc_trace(fit, pars = c("a","b"), np = np_cp) +
  xlab("Iterações")
```
```{r tgca_divergence}
mcmc_nuts_divergence(np_cp, lp_cp)
```

```{r tgca_rhat}
rhats <- rhat(fit)
mcmc_rhat(rhats)
```

```{r}
neff_ncp = neff_ratio(fit, pars = c("a", "b", "theta"))
mcmc_neff(neff_ncp)
```
### Recuparando as estimativas e calculando as medidas:
```{r tgca_calcula_metricas_mix}

fit_summary = summary(fit)

fit_summary$summary

fit_summary$summary[,'50%']

tgca_a2 = fit_summary$summary[,'50%']['a']
tgca_b2 = fit_summary$summary[,'50%']['b']
tgca_p2 = fit_summary$summary[,'50%']['theta']

calcula_dic(dados_tg$tempo/365, dados_tg$cens, log_veros_mix,
           extract(fit, "a") |> unlist(),
           extract(fit, "b") |> unlist(), 
           extract(fit, "theta") |> unlist()) |>
  print(digits = 22)

```

```{r}
fit_def = stan( file = 'codigos_stan/def_tgca.stan',
            data = list(N = nrow(dados_tg), T = dados_tg$tempo/365, D = dados_tg$cens), 
            warmup = 1000, iter = 6000, chains = 2, cores = 2, seed = 154)

```

```{r}
mcmc_dens_overlay(fit_def, pars = c("a", "b"))
```

```{r}
mcmc_trace(fit_def, window = c(1,1000), pars = c("a", "b"),
           facet_args = list(nrow = 2))

```

```{r}
mcmc_trace(fit_def, pars = c("a", "b"),
           facet_args = list(nrow = 2))

```


```{r}
cadeias_df = data.frame(index = 1:length(extract(fit_def, "a")), a = extract(fit_def, "a"), b = extract(fit_def, "b"))

n = 2000

acf_a = ggAcf(cadeias_df[1:n,]$a, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(a))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

acf_b = ggAcf(cadeias_df[1:n,]$b, lag.max = 50) + 
  theme_minimal() +
  labs(title = expression(hat(b))) +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(size=12)) 

gridExtra::grid.arrange(acf_a, acf_b)
```

```{r}
lp_cp = log_posterior(fit_def)
np_cp = nuts_params(fit_def)

#mcmc_parcoord(as.array(fit_def), pars = c("a","b"), np = np_cp)

mcmc_trace(fit_def, pars = c("a","b"), np = np_cp) +
  xlab("Iterações")
```

```{r}
mcmc_nuts_divergence(np_cp, lp_cp)
```

```{r}
rhats <- rhat(fit_def)
mcmc_rhat(rhats)
```

```{r}
neff_ncp = neff_ratio(fit_def, pars = c("a", "b"))
mcmc_neff(neff_ncp)
```
### Recuparando as estimativas e calculando as medidas:
```{r}

fit_summary_def = summary(fit_def)

fit_summary_def$summary

fit_summary_def$summary[,'50%']


tgca_a3 = fit_summary_def$summary[,'50%']['a']
tgca_b3 = fit_summary_def$summary[,'50%']['b']


calcula_dic(dados_tg$tempo/365, dados_tg$cens, log_veros_def,
           extract(fit_def, "a") |> unlist(),
           extract(fit_def, "b") |> unlist(), NULL) |>
  print(digits = 22)

### Figura

x = dados_tg$tempo/365

kaplan_meier_s = survfit(Surv(tempo/365, cens) ~ 1, data = dados_tg)

dados_km = data.frame(kaplan_meier_s$time, kaplan_meier_s$surv, kaplan_meier_s$n.event)
colnames(dados_km) = c('Tempo', 'Sobrevivência', 'Evento')


ggplot() + 
  geom_step(aes(x = Tempo, y = Sobrevivência, colour = "a", linetype = "a"), 
            data = dados_km, size = 1) +
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(x = 'Tempo') +
  theme_minimal() +
  geom_line( 
    mapping=aes(x=x, y = pgompertz(x,tgca_a , #fit_usual_summary$summary[,1]['a']
                                   tgca_b, lower.tail = F), #fit_usual_summary$summary[,1]['b']
                colour = "b", linetype = "b"), 
    size = 1) +
  geom_line( 
    mapping=aes(x=x, y = flexsurv::pgompertz(x, tgca_a3, #fit_summary_def$summary[,1]['a']
                                   tgca_b3, lower.tail = F), #fit_summary_def$summary[,1]['b']
                colour = "c", linetype = "c"), 
    size = 1) +
  geom_line( 
    mapping=aes(x=x, y= tgca_p2 + (1 - tgca_p2)*pgompertz(x, tgca_a2, tgca_b2, lower.tail = F), #fit_summary$summary[,1]['theta'] + (1 - fit_summary$summary[,1]['theta'])*pgompertz(x, fit_summary$summary[,1]['a'],     #fit_summary$summary[,1]['b']
                colour = "d", linetype = "d"), 
    size = 1) +
  ylim(0,1) +
  theme(legend.position = 'bottom', legend.text = element_text(size=16), 
        axis.title.y = element_text(size = 16), axis.text.y = element_text(size = 16),
        legend.key.width= unit(1.5, 'cm'), legend.key.height = unit(0.5, 'cm')) + 
  guides(colour = guide_legend(nrow = 2)) +
  scale_color_manual(name = "",
                     values = c(
                       "royalblue",
                       "springgreen3",
                       'orange',
                       "brown2"),
                     labels = c("Kaplan-Meier","Usual", 
                                "Defeituoso",
                                "Com Mistura")) +
  scale_linetype_manual(name = "", values=c("solid", "twodash", 
                                            "dotted", "dashed"),
                        labels = c("Kaplan-Meier", 
                                   "Usual",
                                   "Defeituoso", 
                                   "Com Mistura"))

ggsave(filename = 'figuras/tgca_bayes.pdf', units = 'in', width = 7, height = 9)

```
